SELECT 
SELECT 
    MIN(FIRST_PURCHASE_MONTH)
    , MAX(FIRST_PURCHASE_MONTH)
FROM KAGGLE_OLIST_DEV.DBT_DEV.FCT_CUSTOMER_COHORT_RETENTION
;
SELECT 
    ROW_NUMBER() OVER (ORDER BY NULL) - 1 AS months_after_first_purchase
FROM TABLE(GENERATOR(ROWCOUNT => 25))
;
USE DATABASE KAGGLE_OLIST_DEV;
USE SCHEMA DBT_DEV;
SELECT * FROM STG_OLIST_ORDER_ITEMS_DATASET;

select
    order_id as unique_field,
    count(*) as n_records

from KAGGLE_OLIST_DEV.DBT_DEV.stg_OLIST_ORDER_ITEMS_DATASET
where order_id is not null
group by order_id
having count(*) > 1
;

SELECT * 
FROM KAGGLE_OLIST_DEV.DBT_DEV.stg_OLIST_ORDER_PAYMENTS_DATASET 
LIMIT 100
;

-- 重複している customer_id が、どんな行になっているかあぶり出す
SELECT 
    CUSTOMER_ID, 
    COUNT(*) as row_cnt
FROM KAGGLE_OLIST_DEV.DBT_DEV.STG_OLIST_ORDERS_DATASET
GROUP BY 1
HAVING row_cnt > 1;
;

USE SCHEMA DBT_DEV;
SELECT 
    CUSTOMER_UNIQUE_ID
    , COUNT(*) AS cnt
FROM KAGGLE_OLIST_DEV.DBT_DEV.STG_OLIST_CUSTOMERS_DATASET
GROUP BY 
    CUSTOMER_UNIQUE_ID
HAVING cnt > 1
;

SELECT 
    GEOLOCATION_ZIP_CODE_PREFIX
    , a.geolocation_city
    , a.geolocation_state
    , a.geolocation_lat
    , a.geolocation_lng
    , COUNT(*) AS cnt
FROM KAGGLE_OLIST_DEV.DBT_DEV.STG_OLIST_GEOLOCATION_DATASET AS a
GROUP BY 1 , 2 , 3, 4, 5
HAVING cnt > 1
;

SELECT * 
FROM KAGGLE_OLIST_DEV.DBT_DEV.STG_OLIST_ORDER_PAYMENTS_DATASET
LIMIT 100
;
FROM KAGGLE_OLIST_DEV.DBT_DEV.STG_MQL_OLIST_MARKETING_QUALIFIED_LEADS_DATASET
SHOW VIEWS IN SCHEMA KAGGLE_OLIST_DEV.PUBLIC;
KAGGLE_OLIST_DEV.DBT_ENVUSE DATABASE KAGGLE_OLIST_DEV;
USE SCHEMA PUBLIC; 
DROP VIEW STG_OLIST_CLOSED_DEALS_DATASET;
DROP VIEW STG_OLIST_CUSTOMERS_DATASET;
DROP VIEW STG_OLIST_GEOLOCATION_DATASET;
DROP VIEW STG_OLIST_MARKETING_QUALIFIED_LEADS_DATASET;
DROP VIEW STG_OLIST_ORDERS_DATASET;
DROP VIEW STG_OLIST_ORDER_ITEMS_DATASET;
DROP VIEW STG_OLIST_ORDER_PAYMENTS_DATASET;
DROP VIEW STG_OLIST_ORDER_REVIEWS_DATASET;
DROP VIEW STG_OLIST_PRODUCTS_DATASET;
DROP VIEW STG_OLIST_SELLERS_DATASET;
DROP VIEW STG_PRODUCT_CATEGORY_NAME_TRANSLATION;

SHOW TABLES IN SCHEMA KAGGLE_OLIST_DEV.PUBLIC;

USE DATABASE KAGGLE_OLIST_DEV;
USE SCHEMA DBT_DEV; 
SHOW VIEWS; 
DROP VIEW STG_OLIST_CLOSED_DEALS_DATASET;
DROP VIEW STG_OLIST_CUSTOMERS_DATASET;
DROP VIEW STG_OLIST_GEOLOCATION_DATASET;
DROP VIEW STG_OLIST_MARKETING_QUALIFIED_LEADS_DATASET;
DROP VIEW STG_OLIST_ORDERS_DATASET;
DROP VIEW STG_OLIST_ORDER_ITEMS_DATASET;
DROP VIEW STG_OLIST_ORDER_PAYMENTS_DATASET;
DROP VIEW STG_OLIST_ORDER_REVIEWS_DATASET;
DROP VIEW STG_OLIST_PRODUCTS_DATASET;
DROP VIEW STG_OLIST_SELLERS_DATASET;
DROP VIEW STG_PRODUCT_CATEGORY_NAME_TRANSLATION;

USE DATABASE KAGGLE_OLIST_DEV;
USE SCHEMA PUBLIC; 
DROP TABLE OLIST_MARKETING_QUALIFIED_LEADS_DATASET;
DROP TABLE OLIST_CLOSED_DEALS_DATASET;
USE DATABASE KAGGLE_OLIST_PROD;
USE SCHEMA PUBLIC; 
DROP TABLE OLIST_MARKETING_QUALIFIED_LEADS_DATASET;
DROP TABLE OLIST_CLOSED_DEALS_DATASET;

