-- 自身のユーザー(または対象のサービスユーザー)に対して適用
ALTER USER MASAHARUURA SET RSA_PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5BpFeQlPzEcAjoJ+cSiA
aZzYH2BKgLFqLfhT5hEtvclmtbvSKHqAgUtEnpDxJ84C+SvhBeK23yMNORgV6yD5
0b9rbDG6ZBgCAt5Vh9OyJzsR4sQlA1aZztZ9l554AH3F5r2FgidHl6dmnndPA/2p
rTT7kuoMCKTdvCRA8JbD6zOKcmdQcchYnGMQtd0SCRt84LuYX9uYoWKbpFxBgkwK
02S1QnBDBIV8XkQsQuPiEV6bHrbpaMbw+G3FHRxMrlCej1wHziuGP2kIFqtW9J7x
GUEE6ZFcXY1jXS8SoxWjza715XDY/uLKULLa590E11VP8S8Uqknopdl755tFnBSc
+QIDAQAB
-----END PUBLIC KEY-----';

DESCRIBE USER MASAHARUURA;

SHOW TABLES;


SHOW VIEWS;
DROP VIEW KAGGLE_OLIST_DEV.DBT_DEV.INT_CUSTOMERS__FIRST_PAYMENT;
DROP VIEW KAGGLE_OLIST_DEV.DBT_DEV.INT_CUSTOMERS__PURCHASE_SUMMARY;

SELECT * FROM FCT_CUSTOMER_COHORT_RETENTION_FULL LIMIT 100;
-- 1. ACCOUNT_ADMIN（最高管理者）に切り替える
USE ROLE ACCOUNTADMIN;

-- 2. Pythonの公式倉庫（pypi.orgと関連サーバー）への通信ルートを定義する
CREATE OR REPLACE NETWORK RULE pypi_network_rule
  MODE = 'EGRESS'
  TYPE = 'HOST_PORT'
  VALUE_LIST = ('pypi.org', 'files.pythonhosted.org', 'pypi.python.org');

-- 3. 通信許可証（EAI）を作成する
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION pypi_access_integration
  ALLOWED_NETWORK_RULES = (pypi_network_rule)
  ENABLED = TRUE;

-- 4. あなたのStreamlitアプリに対して、この通信許可証の使用を許可する
-- (※「アプリ名」の部分は、ご自身の実際のStreamlitアプリの名前に書き換えてください)
ALTER STREAMLIT KAGGLE_OLIST_DEV.DBT_DEV.アプリ名 
  SET EXTERNAL_ACCESS_INTEGRATIONS = (pypi_access_integration);



SELECT 
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY total_orders) AS q25
    , PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY total_orders) AS q50
    , PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY total_orders) AS q75
    , PERCENTILE_CONT(1.0) WITHIN GROUP (ORDER BY total_orders) AS q100
    , MAX(first_purchase_month)
FROM FCT_CUSTOMER_COHORT_RETENTION_FULL 
;

SELECT first_purchase_at::DATE FROM FCT_CUSTOMER_COHORT_RETENTION_FULL LIMIT 10
;

SELECT * FROM DIM_CUSTOMER_LIFECYCLE;
SELECT * FROM KAGGLE_OLIST_DEV.DBT_DEV.FCT_CUSTOMER_COHORT_RETENTION_FULL WHERE customer_unique_id='0280c3bae373e59fd0f564cf9b0188a1';
SELECT 
    MIN(FIRST_PURCHASE_MONTH)
    , MAX(FIRST_PURCHASE_MONTH)
FROM KAGGLE_OLIST_DEV.DBT_DEV.FCT_CUSTOMER_COHORT_RETENTION
;
SELECT 
    ROW_NUMBER() OVER (ORDER BY NULL) - 1 AS months_after_first_purchase
FROM TABLE(GENERATOR(ROWCOUNT => 25))
;
USE DATABASE KAGGLE_OLIST_DEV;
USE SCHEMA DBT_DEV;
SELECT * FROM STG_OLIST_ORDER_ITEMS_DATASET;

select
    order_id as unique_field,
    count(*) as n_records

from KAGGLE_OLIST_DEV.DBT_DEV.stg_OLIST_ORDER_ITEMS_DATASET
where order_id is not null
group by order_id
having count(*) > 1
;

SELECT * 
FROM KAGGLE_OLIST_DEV.DBT_DEV.stg_OLIST_ORDER_PAYMENTS_DATASET 
LIMIT 100
;

-- 重複している customer_id が、どんな行になっているかあぶり出す
SELECT 
    CUSTOMER_ID, 
    COUNT(*) as row_cnt
FROM KAGGLE_OLIST_DEV.DBT_DEV.STG_OLIST_ORDERS_DATASET
GROUP BY 1
HAVING row_cnt > 1;
;

USE SCHEMA DBT_DEV;
SELECT 
    CUSTOMER_UNIQUE_ID
    , COUNT(*) AS cnt
FROM KAGGLE_OLIST_DEV.DBT_DEV.STG_OLIST_CUSTOMERS_DATASET
GROUP BY 
    CUSTOMER_UNIQUE_ID
HAVING cnt > 1
;

SELECT 
    GEOLOCATION_ZIP_CODE_PREFIX
    , a.geolocation_city
    , a.geolocation_state
    , a.geolocation_lat
    , a.geolocation_lng
    , COUNT(*) AS cnt
FROM KAGGLE_OLIST_DEV.DBT_DEV.STG_OLIST_GEOLOCATION_DATASET AS a
GROUP BY 1 , 2 , 3, 4, 5
HAVING cnt > 1
;

SELECT * 
FROM KAGGLE_OLIST_DEV.DBT_DEV.STG_OLIST_ORDER_PAYMENTS_DATASET
LIMIT 100
;
FROM KAGGLE_OLIST_DEV.DBT_DEV.STG_MQL_OLIST_MARKETING_QUALIFIED_LEADS_DATASET
SHOW VIEWS IN SCHEMA KAGGLE_OLIST_DEV.PUBLIC;
KAGGLE_OLIST_DEV.DBT_ENVUSE DATABASE KAGGLE_OLIST_DEV;
USE SCHEMA PUBLIC; 
DROP VIEW STG_OLIST_CLOSED_DEALS_DATASET;
DROP VIEW STG_OLIST_CUSTOMERS_DATASET;
DROP VIEW STG_OLIST_GEOLOCATION_DATASET;
DROP VIEW STG_OLIST_MARKETING_QUALIFIED_LEADS_DATASET;
DROP VIEW STG_OLIST_ORDERS_DATASET;
DROP VIEW STG_OLIST_ORDER_ITEMS_DATASET;
DROP VIEW STG_OLIST_ORDER_PAYMENTS_DATASET;
DROP VIEW STG_OLIST_ORDER_REVIEWS_DATASET;
DROP VIEW STG_OLIST_PRODUCTS_DATASET;
DROP VIEW STG_OLIST_SELLERS_DATASET;
DROP VIEW STG_PRODUCT_CATEGORY_NAME_TRANSLATION;

SHOW TABLES IN SCHEMA KAGGLE_OLIST_DEV.PUBLIC;

USE DATABASE KAGGLE_OLIST_DEV;
USE SCHEMA DBT_DEV; 
SHOW VIEWS; 
DROP VIEW STG_OLIST_CLOSED_DEALS_DATASET;
DROP VIEW STG_OLIST_CUSTOMERS_DATASET;
DROP VIEW STG_OLIST_GEOLOCATION_DATASET;
DROP VIEW STG_OLIST_MARKETING_QUALIFIED_LEADS_DATASET;
DROP VIEW STG_OLIST_ORDERS_DATASET;
DROP VIEW STG_OLIST_ORDER_ITEMS_DATASET;
DROP VIEW STG_OLIST_ORDER_PAYMENTS_DATASET;
DROP VIEW STG_OLIST_ORDER_REVIEWS_DATASET;
DROP VIEW STG_OLIST_PRODUCTS_DATASET;
DROP VIEW STG_OLIST_SELLERS_DATASET;
DROP VIEW STG_PRODUCT_CATEGORY_NAME_TRANSLATION;

USE DATABASE KAGGLE_OLIST_DEV;
USE SCHEMA PUBLIC; 
DROP TABLE OLIST_MARKETING_QUALIFIED_LEADS_DATASET;
DROP TABLE OLIST_CLOSED_DEALS_DATASET;
USE DATABASE KAGGLE_OLIST_PROD;
USE SCHEMA PUBLIC; 
DROP TABLE OLIST_MARKETING_QUALIFIED_LEADS_DATASET;
DROP TABLE OLIST_CLOSED_DEALS_DATASET;

