USE DATABASE KAGGLE_OLIST_DEV;
USE SCHEMA KAGGLE_OLIST_DEV.DBT_DEV;
CREATE SCHEMA KAGGLE_OLIST_DEV.TEMP;

DESCRIBE TABLE KAGGLE_OLIST_DEV.DBT_DEV.STG_OLIST_CUSTOMERS_DATASET
;
CREATE SCHEMA KAGGLE_OLIST_DEV.TEMP;
CREATE OR REPLACE TABLE KAGGLE_OLIST_DEV.TEMP.CUSTOMERS CLONE KAGGLE_OLIST_DEV.PUBLIC.OLIST_CUSTOMERS_DATASET
;


COPY INTO KAGGLE_OLIST_DEV.TEMP.CUSTOMERS FROM @KAGGLE_OLIST_DEV.PUBLIC.KAGGLE_OLIST/kaggle_olist.zip
FILE_FORMAT=(
    TYPE = 'CSV'
    COMPRESSION='AUTO'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    ON_ERROR = 'SKIP_FILE'
);